keys:
  - &mac1chng age142e54afjeqajz4pgdc30tj8u6cjnyppj9ef3xjv4keqmk7pjcc2sfhk29x
  - &dsk1chng age1tazzcv0l5r3lxwhah0nhgych2t6najenza5w9s753az444qr5ekq68fp3v
  - &svr1chng age1w4tgfu8upwhpsm76sfuwls6f2suw6teurgz740lhv49v23h2scyqfzpmq7
  - &svr2chng age1sfxy5j2wmklxsmm4fsdgd4378zmc29sa5p4vylw5fnqd8sqtt5rs5jwvpg
  - &svr3chng age19uv62f9stfhhlsyckmg5ll2t6c8dd4f6nytnd95ftl6v62js3fmq6g2ktk
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *mac1chng
          - *dsk1chng
          - *svr1chng
          - *svr2chng
          - *svr3chng
