keys:
  - &mac1chng age142e54afjeqajz4pgdc30tj8u6cjnyppj9ef3xjv4keqmk7pjcc2sfhk29x
  - &dsk1chng age1tazzcv0l5r3lxwhah0nhgych2t6najenza5w9s753az444qr5ekq68fp3v
  - &svr1chng age1w4tgfu8upwhpsm76sfuwls6f2suw6teurgz740lhv49v23h2scyqfzpmq7
  - &svr2chng age15x98sl9fgs7gqm66r2a0lya2r4was6rgtrw5p9as3s6nzhepep8qmh8s72
  - &svr3chng age13v6dlnrjpeyxgdh8jr3yz0l4pqgp09kwtejsun9ptfdchekx74lst4lk6d
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *mac1chng
          - *dsk1chng
          - *svr1chng
          - *svr2chng
          - *svr3chng
